version: 2

project_name: metabase-mcp-server

builds:
  - main: ./cmd/metabase-mcp-server
    binary: metabase-mcp-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - image_templates:
      - "ghcr.io/anaryk/metabase-mcp-server:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/anaryk/metabase-mcp-server"
    goarch: amd64
  - image_templates:
      - "ghcr.io/anaryk/metabase-mcp-server:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/anaryk/metabase-mcp-server"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/anaryk/metabase-mcp-server:{{ .Version }}"
    image_templates:
      - "ghcr.io/anaryk/metabase-mcp-server:{{ .Version }}-amd64"
      - "ghcr.io/anaryk/metabase-mcp-server:{{ .Version }}-arm64"
  - name_template: "ghcr.io/anaryk/metabase-mcp-server:latest"
    image_templates:
      - "ghcr.io/anaryk/metabase-mcp-server:{{ .Version }}-amd64"
      - "ghcr.io/anaryk/metabase-mcp-server:{{ .Version }}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
